import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1701694234520 implements MigrationInterface {
    name = 'InitMigration1701694234520'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "disability-assessments" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "hasADisability" boolean NOT NULL DEFAULT false, "originDisability" character varying NOT NULL, CONSTRAINT "PK_4652e7f9586de6c3a528b89fa04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "analysis-cases" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "coherence" boolean NOT NULL DEFAULT false, "hypothesis" character varying NOT NULL, "justification" character varying NOT NULL, "observations" character varying NOT NULL, "requestId" integer, CONSTRAINT "REL_b665b0e8078516816572651674" UNIQUE ("requestId"), CONSTRAINT "PK_42dfef260d43cd5a2e9f3b917df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branch-offices" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "province" character varying NOT NULL, "municipality" character varying NOT NULL, "street" character varying NOT NULL, "noStreet" character varying NOT NULL, CONSTRAINT "PK_1634abf35e49fef9cb818ddeee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service-appointments" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "service" character varying NOT NULL, CONSTRAINT "PK_31a639f2719afb2fe3a8157e2eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "startAt" TIMESTAMP NOT NULL, "endAt" TIMESTAMP NOT NULL, "branchOfficeId" integer NOT NULL, "serviceAppointmentId" integer NOT NULL, CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disease-history" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "disease" character varying NOT NULL, CONSTRAINT "PK_f718468254a907441b7ef73f606" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "maternal-histories" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "reason" character varying, "biomedicalId" integer NOT NULL, CONSTRAINT "REL_80cceb61be6bd21ad5b8968a7f" UNIQUE ("biomedicalId"), CONSTRAINT "PK_0cbf2190b6949582a9e58af099c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "health-issues" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "origin" character varying NOT NULL, CONSTRAINT "PK_d90807c7d82bc7af1cee46eb402" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "origin-medical-conditions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "relevantFamilyHistory" character varying, "biomedicalId" integer NOT NULL, CONSTRAINT "REL_ac046a3f787b2f1858f0e3889a" UNIQUE ("biomedicalId"), CONSTRAINT "PK_952eac24fe2566e1e66505612ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "perinatal-histories" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ageGestional" character varying NOT NULL, "birthWeightPoundsLb" integer NOT NULL, "headCircumferenceCm" integer NOT NULL, "revival" boolean NOT NULL, "apgar" integer, "reason" character varying, "biomedicalId" integer NOT NULL, CONSTRAINT "REL_4f20980469108e5c8793584e93" UNIQUE ("biomedicalId"), CONSTRAINT "PK_3a4c306ffc55537ab5d1d395f18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "international-classification-of-diseases" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_3ac73375c91cbb6aa8b0866e4f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "biomedicals" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "requestId" integer NOT NULL, CONSTRAINT "REL_aea07b2976ba5bea3b2c4cfc0d" UNIQUE ("requestId"), CONSTRAINT "PK_2fe27d66b31ed57f744270f6701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "communications" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "method" character varying NOT NULL, CONSTRAINT "PK_29ec793018d5d5ca19d40149e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question-factors" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "question" character varying NOT NULL, "category" character varying NOT NULL, CONSTRAINT "PK_11ef9f8f950a7964cb57595983e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contextual-factor-questions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "questionFactorId" integer NOT NULL, "contextualFactorId" integer NOT NULL, "value" character varying NOT NULL, "reason" character varying, CONSTRAINT "PK_ee23609dd90daaa14478fdb432b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "support-products" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "category" character varying NOT NULL, CONSTRAINT "PK_d7ef5ef146731e60bcd2684e0f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "support-products-request" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "supportProductId" integer NOT NULL, "contextualFactorId" integer NOT NULL, "needAndHave" boolean, "needAndDoNotHave" boolean, CONSTRAINT "PK_9724499c95ced543de5572842bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contextual-factors" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "requestId" integer NOT NULL, CONSTRAINT "REL_aa2550f12969f7f826dcaf9fd5" UNIQUE ("requestId"), CONSTRAINT "PK_6954099aa57a502087613156c56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "code" character varying NOT NULL, "question" character varying NOT NULL, "category" character varying NOT NULL, "formId" integer NOT NULL, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."forms_type_enum" AS ENUM('BABY', 'CHILD', 'CHILDREN_AND_YOUTH', 'ADULT')`);
        await queryRunner.query(`CREATE TABLE "forms" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "title" character varying NOT NULL, "type" "public"."forms_type_enum" NOT NULL, CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form-requests" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "formId" integer NOT NULL, "questionId" integer NOT NULL, "requestId" integer NOT NULL, "value" integer NOT NULL, CONSTRAINT "PK_1998623a4a2389c23c4c69acffb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "motives-request" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "motive" character varying NOT NULL, CONSTRAINT "PK_b316de36ea68c21ae8d9db4723f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reconsideration-requests" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "disagreementDenial" boolean NOT NULL DEFAULT false, "disagreementCertification" boolean NOT NULL DEFAULT false, "disabilityOrigin" boolean NOT NULL DEFAULT false, "disabilityExistence" boolean NOT NULL DEFAULT false, "reason" character varying NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "REL_2d6d0e59b5b35f639271e8637d" UNIQUE ("requestId"), CONSTRAINT "PK_b328ec2c7fd2d42cfc8c6fe1722" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request-contexts" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "description" character varying NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "REL_30a8088b8ef1b135844c0a72f5" UNIQUE ("requestId"), CONSTRAINT "PK_cf82347959495612d4bff89d0ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."requests_type_enum" AS ENUM('INITIAL_EVALUATION', 'VALUATION_BY_CHANGE')`);
        await queryRunner.query(`CREATE TYPE "public"."requests_status_enum" AS ENUM('PROGRESS', 'CERTIFICATE', 'PAUSED', 'DENIED')`);
        await queryRunner.query(`CREATE TABLE "requests" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "type" "public"."requests_type_enum" NOT NULL, "status" "public"."requests_status_enum" NOT NULL, "caseCode" character varying NOT NULL, "reason" character varying, CONSTRAINT "PK_0428f484e96f9e6a55955f29b5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_type_enum" AS ENUM('DOCUMENT')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "fileName" character varying NOT NULL, "type" "public"."files_type_enum" NOT NULL, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user-address-streets" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "address" character varying NOT NULL, "province" character varying NOT NULL, "municipality" character varying NOT NULL, "noStreet" character varying NOT NULL, "userId" integer NOT NULL, CONSTRAINT "REL_c8e76646eafb2e8f7f75615701" UNIQUE ("userId"), CONSTRAINT "PK_6fe0209e97107b17889321ccb52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user-passwords" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "password" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "userId" integer NOT NULL, "expiredAt" date NOT NULL, CONSTRAINT "PK_c93d946f4bca64b3f41341ab3a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role-permissions" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, "create" boolean NOT NULL DEFAULT false, "read" boolean NOT NULL DEFAULT false, "update" boolean NOT NULL DEFAULT false, "delete" boolean NOT NULL DEFAULT false, "page" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f1e88f21bc89a8b5456a656dbd5" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user-permissions" ("permissionId" integer NOT NULL, "userId" integer NOT NULL, "create" boolean NOT NULL DEFAULT false, "read" boolean NOT NULL DEFAULT false, "update" boolean NOT NULL DEFAULT false, "delete" boolean NOT NULL DEFAULT false, "page" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_806ad998baacf05fc28a60363b3" PRIMARY KEY ("permissionId", "userId"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "active" boolean NOT NULL, "roleId" integer NOT NULL, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user-info_identificationtype_enum" AS ENUM('ID_CARD', 'PASSPORT', 'NUI')`);
        await queryRunner.query(`CREATE TYPE "public"."user-info_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "user-info" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userName" character varying NOT NULL, "nationality" character varying NOT NULL, "identification" character varying NOT NULL, "identificationType" "public"."user-info_identificationtype_enum" NOT NULL, "birthDate" TIMESTAMP WITH TIME ZONE NOT NULL, "phone" character varying NOT NULL, "mobile" character varying NOT NULL, "gender" "public"."user-info_gender_enum" NOT NULL, "conversationAbility" boolean NOT NULL DEFAULT true, "institutionName" character varying, "rnc" character varying, "institutionPosition" character varying, "userId" integer NOT NULL, CONSTRAINT "REL_737595561345b87f0f377f019b" UNIQUE ("userId"), CONSTRAINT "PK_17470eb7d3fd325d9c872551fc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "therapeutic-interventions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "description" character varying, "optionsExhausted" boolean NOT NULL DEFAULT false, "permanentOrLongTerm" boolean NOT NULL DEFAULT false, "degenerativeCondition" boolean NOT NULL DEFAULT false, "anosognosia" boolean NOT NULL DEFAULT false, "deafblindnessDiagnosis" boolean NOT NULL DEFAULT false, "dementiaDiagnosis" boolean NOT NULL DEFAULT false, "emotionalLability" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3b31d27db9d01a759376f704e4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "treating-physicians" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "exequatur" character varying NOT NULL, "specialty" character varying NOT NULL, "pss" character varying NOT NULL, "healthRegion" character varying NOT NULL, "healthArea" character varying NOT NULL, "healthZone" character varying NOT NULL, CONSTRAINT "PK_29236de5dc125c05797d3c04b11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "disability" ("analysisCaseId" integer NOT NULL, "disabilityAssessmentId" integer NOT NULL, CONSTRAINT "PK_081483fd78d1b90318e8ba306b2" PRIMARY KEY ("analysisCaseId", "disabilityAssessmentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e1282e9b626d63a610fa5ac2e" ON "disability" ("analysisCaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_156b26e066efaa3356529d9e8c" ON "disability" ("disabilityAssessmentId") `);
        await queryRunner.query(`CREATE TABLE "maternal-disease-histories" ("diseaseHistoryId" integer NOT NULL, "maternalHistoryId" integer NOT NULL, CONSTRAINT "PK_3688a08379f37cbe24d0bb0fb8f" PRIMARY KEY ("diseaseHistoryId", "maternalHistoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7ee4690eaf3ae2b50a5233044" ON "maternal-disease-histories" ("diseaseHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c5ebffc3bf6f324b7d0776b82" ON "maternal-disease-histories" ("maternalHistoryId") `);
        await queryRunner.query(`CREATE TABLE "origin-medical-health-issues" ("healthIssueId" integer NOT NULL, "originMedicalConditionId" integer NOT NULL, CONSTRAINT "PK_ad26a0458fdaccad327f8bf34ed" PRIMARY KEY ("healthIssueId", "originMedicalConditionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9c3d82eb464743cc83c75f839" ON "origin-medical-health-issues" ("healthIssueId") `);
        await queryRunner.query(`CREATE INDEX "IDX_056cdac14043dbda6d52437f74" ON "origin-medical-health-issues" ("originMedicalConditionId") `);
        await queryRunner.query(`CREATE TABLE "perinatal-disease-histories" ("diseaseHistoryId" integer NOT NULL, "perinatalHistoryId" integer NOT NULL, CONSTRAINT "PK_f3a7d458c120a5e627198f15469" PRIMARY KEY ("diseaseHistoryId", "perinatalHistoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2a3418fee48e88e60cae76755" ON "perinatal-disease-histories" ("diseaseHistoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_38e83825597a5fae46d789db6e" ON "perinatal-disease-histories" ("perinatalHistoryId") `);
        await queryRunner.query(`CREATE TABLE "biomedical-international-classification-of-diseases" ("biomedicalId" integer NOT NULL, "classificationDiseaseId" integer NOT NULL, CONSTRAINT "PK_3949515ec7b8e61cc65a2a56caa" PRIMARY KEY ("biomedicalId", "classificationDiseaseId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b029cb5a7e2b4a849a1e712c8c" ON "biomedical-international-classification-of-diseases" ("biomedicalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a694303dff07a4250575d3229" ON "biomedical-international-classification-of-diseases" ("classificationDiseaseId") `);
        await queryRunner.query(`CREATE TABLE "reconsideration-files" ("reconsideration-requests" integer NOT NULL, "files" integer NOT NULL, CONSTRAINT "PK_26b511f1bb99e6c7b47bde0e025" PRIMARY KEY ("reconsideration-requests", "files"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6cac12e5ff3e6a1fa0ccd331aa" ON "reconsideration-files" ("reconsideration-requests") `);
        await queryRunner.query(`CREATE INDEX "IDX_609c6a14cfe70bdabb6ef7aa49" ON "reconsideration-files" ("files") `);
        await queryRunner.query(`CREATE TABLE "communication-requests" ("communicationId" integer NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "PK_f79af94b7fa2c74e47b4907238c" PRIMARY KEY ("communicationId", "requestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c472202a0faa6503c12e6227a4" ON "communication-requests" ("communicationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_004eec3a045ab8b54888a6669f" ON "communication-requests" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "reason-request" ("motiveId" integer NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "PK_938c1bc78a9c0dc9851dc3aaeb1" PRIMARY KEY ("motiveId", "requestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e193155038b8f9b9dc01ffb2b1" ON "reason-request" ("motiveId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e87bbd531517d343119ee116d" ON "reason-request" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "request-appointments" ("requestId" integer NOT NULL, "appointmentId" integer NOT NULL, CONSTRAINT "PK_5458ecb3998f12872dead13d9a2" PRIMARY KEY ("requestId", "appointmentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_931d81402f4018949cfe9fea24" ON "request-appointments" ("requestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98a4b87b5db2d5ec1256c9d0c3" ON "request-appointments" ("appointmentId") `);
        await queryRunner.query(`CREATE TABLE "request-files" ("fileId" integer NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "PK_8af7d51b72020751fd97bec5e4e" PRIMARY KEY ("fileId", "requestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c5d49318519a39ae9426da473" ON "request-files" ("fileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3da67687042d9e8fff6a6654a" ON "request-files" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "user-applicant-patients" ("applicantId" integer NOT NULL, "patientId" integer NOT NULL, CONSTRAINT "PK_bbd24db9e3d943f5c555a77e849" PRIMARY KEY ("applicantId", "patientId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9d89d8ef9fd3fb9bf228629c4" ON "user-applicant-patients" ("applicantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_888eebb3ec48da5a35b2971096" ON "user-applicant-patients" ("patientId") `);
        await queryRunner.query(`CREATE TABLE "user-files" ("userId" integer NOT NULL, "fileId" integer NOT NULL, CONSTRAINT "PK_52743cb0dec4d66d77e904ca31f" PRIMARY KEY ("userId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8baf6a8ede8bd020f135a4272b" ON "user-files" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b1870a0bf21f1f926d3943d24" ON "user-files" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "user-requests" ("userId" integer NOT NULL, "requestId" integer NOT NULL, CONSTRAINT "PK_da72413b270c6c8741c5b7be847" PRIMARY KEY ("userId", "requestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_258bb0521512603b79ad2017d7" ON "user-requests" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b2bc49db43ea90db7b9041347" ON "user-requests" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "treating-physician-therapeutic-interventions" ("treatingPhysicianId" integer NOT NULL, "therapeuticInterventionId" integer NOT NULL, CONSTRAINT "PK_e19260cc7b48d8cdba796762b97" PRIMARY KEY ("treatingPhysicianId", "therapeuticInterventionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3bf0631670016021cb0ac15e1" ON "treating-physician-therapeutic-interventions" ("treatingPhysicianId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7cc567f63ece1a0cf04bf86e7" ON "treating-physician-therapeutic-interventions" ("therapeuticInterventionId") `);
        await queryRunner.query(`CREATE TABLE "treating-physicians-requests" ("treating-physician" integer NOT NULL, "biomedical" integer NOT NULL, CONSTRAINT "PK_8370f56a8733f769a44ffe442b6" PRIMARY KEY ("treating-physician", "biomedical"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77071a540de3478df89f4b1b10" ON "treating-physicians-requests" ("treating-physician") `);
        await queryRunner.query(`CREATE INDEX "IDX_d49e50167d6994a3ec79063b32" ON "treating-physicians-requests" ("biomedical") `);
        await queryRunner.query(`ALTER TABLE "analysis-cases" ADD CONSTRAINT "FK_b665b0e8078516816572651674e" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_b8bc48e128daefdb56982dd122e" FOREIGN KEY ("branchOfficeId") REFERENCES "branch-offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_2b475230c3a4f66ba8220d3b0d3" FOREIGN KEY ("serviceAppointmentId") REFERENCES "service-appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maternal-histories" ADD CONSTRAINT "FK_80cceb61be6bd21ad5b8968a7f0" FOREIGN KEY ("biomedicalId") REFERENCES "biomedicals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "origin-medical-conditions" ADD CONSTRAINT "FK_ac046a3f787b2f1858f0e3889ae" FOREIGN KEY ("biomedicalId") REFERENCES "biomedicals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perinatal-histories" ADD CONSTRAINT "FK_4f20980469108e5c8793584e933" FOREIGN KEY ("biomedicalId") REFERENCES "biomedicals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "biomedicals" ADD CONSTRAINT "FK_aea07b2976ba5bea3b2c4cfc0d8" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contextual-factor-questions" ADD CONSTRAINT "FK_16bc53284ed6f32ac9a3c20d9fa" FOREIGN KEY ("questionFactorId") REFERENCES "question-factors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contextual-factor-questions" ADD CONSTRAINT "FK_6797a24e092c9d014bb408a19eb" FOREIGN KEY ("contextualFactorId") REFERENCES "contextual-factors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support-products-request" ADD CONSTRAINT "FK_365152911d94485c7dff0d60832" FOREIGN KEY ("supportProductId") REFERENCES "support-products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support-products-request" ADD CONSTRAINT "FK_37ff38de82808f1881f809a25b8" FOREIGN KEY ("contextualFactorId") REFERENCES "contextual-factors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contextual-factors" ADD CONSTRAINT "FK_aa2550f12969f7f826dcaf9fd5e" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_e635f8de2abc09c58f97c5ce70e" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form-requests" ADD CONSTRAINT "FK_e97d78e6f5ebf0ba0f2027e0dcc" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form-requests" ADD CONSTRAINT "FK_30c457ae8403a4f288d34c003d4" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form-requests" ADD CONSTRAINT "FK_e364eaa655ada96d02fdcf3b5e6" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reconsideration-requests" ADD CONSTRAINT "FK_2d6d0e59b5b35f639271e8637d7" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request-contexts" ADD CONSTRAINT "FK_30a8088b8ef1b135844c0a72f5d" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-address-streets" ADD CONSTRAINT "FK_c8e76646eafb2e8f7f75615701a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-passwords" ADD CONSTRAINT "FK_5206638ec85da31e05b0a12f0a7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role-permissions" ADD CONSTRAINT "FK_832f9475661d055310963d2f20d" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role-permissions" ADD CONSTRAINT "FK_92ee53f7b01b6aaf1e6eac3297e" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-permissions" ADD CONSTRAINT "FK_5012f73c39824319d792beb4a14" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-permissions" ADD CONSTRAINT "FK_95ae8c92259717c22ced22437bc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-info" ADD CONSTRAINT "FK_737595561345b87f0f377f019ba" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disability" ADD CONSTRAINT "FK_4e1282e9b626d63a610fa5ac2e1" FOREIGN KEY ("analysisCaseId") REFERENCES "analysis-cases"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "disability" ADD CONSTRAINT "FK_156b26e066efaa3356529d9e8c1" FOREIGN KEY ("disabilityAssessmentId") REFERENCES "disability-assessments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "maternal-disease-histories" ADD CONSTRAINT "FK_b7ee4690eaf3ae2b50a52330440" FOREIGN KEY ("diseaseHistoryId") REFERENCES "maternal-histories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "maternal-disease-histories" ADD CONSTRAINT "FK_2c5ebffc3bf6f324b7d0776b827" FOREIGN KEY ("maternalHistoryId") REFERENCES "disease-history"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "origin-medical-health-issues" ADD CONSTRAINT "FK_f9c3d82eb464743cc83c75f839f" FOREIGN KEY ("healthIssueId") REFERENCES "origin-medical-conditions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "origin-medical-health-issues" ADD CONSTRAINT "FK_056cdac14043dbda6d52437f74f" FOREIGN KEY ("originMedicalConditionId") REFERENCES "health-issues"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "perinatal-disease-histories" ADD CONSTRAINT "FK_d2a3418fee48e88e60cae767553" FOREIGN KEY ("diseaseHistoryId") REFERENCES "perinatal-histories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "perinatal-disease-histories" ADD CONSTRAINT "FK_38e83825597a5fae46d789db6e8" FOREIGN KEY ("perinatalHistoryId") REFERENCES "disease-history"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "biomedical-international-classification-of-diseases" ADD CONSTRAINT "FK_b029cb5a7e2b4a849a1e712c8c9" FOREIGN KEY ("biomedicalId") REFERENCES "biomedicals"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "biomedical-international-classification-of-diseases" ADD CONSTRAINT "FK_7a694303dff07a4250575d3229d" FOREIGN KEY ("classificationDiseaseId") REFERENCES "international-classification-of-diseases"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reconsideration-files" ADD CONSTRAINT "FK_6cac12e5ff3e6a1fa0ccd331aa8" FOREIGN KEY ("reconsideration-requests") REFERENCES "reconsideration-requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reconsideration-files" ADD CONSTRAINT "FK_609c6a14cfe70bdabb6ef7aa496" FOREIGN KEY ("files") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "communication-requests" ADD CONSTRAINT "FK_c472202a0faa6503c12e6227a43" FOREIGN KEY ("communicationId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "communication-requests" ADD CONSTRAINT "FK_004eec3a045ab8b54888a6669f1" FOREIGN KEY ("requestId") REFERENCES "communications"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reason-request" ADD CONSTRAINT "FK_e193155038b8f9b9dc01ffb2b1b" FOREIGN KEY ("motiveId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reason-request" ADD CONSTRAINT "FK_3e87bbd531517d343119ee116d4" FOREIGN KEY ("requestId") REFERENCES "motives-request"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request-appointments" ADD CONSTRAINT "FK_931d81402f4018949cfe9fea247" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request-appointments" ADD CONSTRAINT "FK_98a4b87b5db2d5ec1256c9d0c3a" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request-files" ADD CONSTRAINT "FK_1c5d49318519a39ae9426da4738" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "request-files" ADD CONSTRAINT "FK_b3da67687042d9e8fff6a6654a1" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-applicant-patients" ADD CONSTRAINT "FK_e9d89d8ef9fd3fb9bf228629c41" FOREIGN KEY ("applicantId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-applicant-patients" ADD CONSTRAINT "FK_888eebb3ec48da5a35b29710967" FOREIGN KEY ("patientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-files" ADD CONSTRAINT "FK_8baf6a8ede8bd020f135a4272b2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-files" ADD CONSTRAINT "FK_3b1870a0bf21f1f926d3943d246" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-requests" ADD CONSTRAINT "FK_258bb0521512603b79ad2017d7d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user-requests" ADD CONSTRAINT "FK_5b2bc49db43ea90db7b9041347e" FOREIGN KEY ("requestId") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "treating-physician-therapeutic-interventions" ADD CONSTRAINT "FK_b3bf0631670016021cb0ac15e14" FOREIGN KEY ("treatingPhysicianId") REFERENCES "treating-physicians"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "treating-physician-therapeutic-interventions" ADD CONSTRAINT "FK_d7cc567f63ece1a0cf04bf86e7e" FOREIGN KEY ("therapeuticInterventionId") REFERENCES "therapeutic-interventions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "treating-physicians-requests" ADD CONSTRAINT "FK_77071a540de3478df89f4b1b10e" FOREIGN KEY ("treating-physician") REFERENCES "treating-physicians"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "treating-physicians-requests" ADD CONSTRAINT "FK_d49e50167d6994a3ec79063b320" FOREIGN KEY ("biomedical") REFERENCES "biomedicals"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`CREATE VIEW "request-view" AS 
    select
        r.*,
        CONCAT(u."firstName", ' ', u."lastName") as "fullName",
        ui.identification,
        ui.rnc,
        ui."institutionName",
        ur."userId" 
    from requests r 
    join "user-requests" ur ON r.id = ur."requestId" 
    left join users u on u.id = ur."userId"
    left join "user-info" ui on ui."userId" = u.id 
    `);
        await queryRunner.query(`INSERT INTO "public"."typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["public","VIEW","request-view","select\n        r.*,\n        CONCAT(u.\"firstName\", ' ', u.\"lastName\") as \"fullName\",\n        ui.identification,\n        ui.rnc,\n        ui.\"institutionName\",\n        ur.\"userId\" \n    from requests r \n    join \"user-requests\" ur ON r.id = ur.\"requestId\" \n    left join users u on u.id = ur.\"userId\"\n    left join \"user-info\" ui on ui.\"userId\" = u.id"]);
        await queryRunner.query(`CREATE TABLE "query-result-cache" ("id" SERIAL NOT NULL, "identifier" character varying, "time" bigint NOT NULL, "duration" integer NOT NULL, "query" text NOT NULL, "result" text NOT NULL, CONSTRAINT "PK_6a98f758d8bfd010e7e10ffd3d3" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "query-result-cache"`);
        await queryRunner.query(`DELETE FROM "public"."typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","request-view","public"]);
        await queryRunner.query(`DROP VIEW "request-view"`);
        await queryRunner.query(`ALTER TABLE "treating-physicians-requests" DROP CONSTRAINT "FK_d49e50167d6994a3ec79063b320"`);
        await queryRunner.query(`ALTER TABLE "treating-physicians-requests" DROP CONSTRAINT "FK_77071a540de3478df89f4b1b10e"`);
        await queryRunner.query(`ALTER TABLE "treating-physician-therapeutic-interventions" DROP CONSTRAINT "FK_d7cc567f63ece1a0cf04bf86e7e"`);
        await queryRunner.query(`ALTER TABLE "treating-physician-therapeutic-interventions" DROP CONSTRAINT "FK_b3bf0631670016021cb0ac15e14"`);
        await queryRunner.query(`ALTER TABLE "user-requests" DROP CONSTRAINT "FK_5b2bc49db43ea90db7b9041347e"`);
        await queryRunner.query(`ALTER TABLE "user-requests" DROP CONSTRAINT "FK_258bb0521512603b79ad2017d7d"`);
        await queryRunner.query(`ALTER TABLE "user-files" DROP CONSTRAINT "FK_3b1870a0bf21f1f926d3943d246"`);
        await queryRunner.query(`ALTER TABLE "user-files" DROP CONSTRAINT "FK_8baf6a8ede8bd020f135a4272b2"`);
        await queryRunner.query(`ALTER TABLE "user-applicant-patients" DROP CONSTRAINT "FK_888eebb3ec48da5a35b29710967"`);
        await queryRunner.query(`ALTER TABLE "user-applicant-patients" DROP CONSTRAINT "FK_e9d89d8ef9fd3fb9bf228629c41"`);
        await queryRunner.query(`ALTER TABLE "request-files" DROP CONSTRAINT "FK_b3da67687042d9e8fff6a6654a1"`);
        await queryRunner.query(`ALTER TABLE "request-files" DROP CONSTRAINT "FK_1c5d49318519a39ae9426da4738"`);
        await queryRunner.query(`ALTER TABLE "request-appointments" DROP CONSTRAINT "FK_98a4b87b5db2d5ec1256c9d0c3a"`);
        await queryRunner.query(`ALTER TABLE "request-appointments" DROP CONSTRAINT "FK_931d81402f4018949cfe9fea247"`);
        await queryRunner.query(`ALTER TABLE "reason-request" DROP CONSTRAINT "FK_3e87bbd531517d343119ee116d4"`);
        await queryRunner.query(`ALTER TABLE "reason-request" DROP CONSTRAINT "FK_e193155038b8f9b9dc01ffb2b1b"`);
        await queryRunner.query(`ALTER TABLE "communication-requests" DROP CONSTRAINT "FK_004eec3a045ab8b54888a6669f1"`);
        await queryRunner.query(`ALTER TABLE "communication-requests" DROP CONSTRAINT "FK_c472202a0faa6503c12e6227a43"`);
        await queryRunner.query(`ALTER TABLE "reconsideration-files" DROP CONSTRAINT "FK_609c6a14cfe70bdabb6ef7aa496"`);
        await queryRunner.query(`ALTER TABLE "reconsideration-files" DROP CONSTRAINT "FK_6cac12e5ff3e6a1fa0ccd331aa8"`);
        await queryRunner.query(`ALTER TABLE "biomedical-international-classification-of-diseases" DROP CONSTRAINT "FK_7a694303dff07a4250575d3229d"`);
        await queryRunner.query(`ALTER TABLE "biomedical-international-classification-of-diseases" DROP CONSTRAINT "FK_b029cb5a7e2b4a849a1e712c8c9"`);
        await queryRunner.query(`ALTER TABLE "perinatal-disease-histories" DROP CONSTRAINT "FK_38e83825597a5fae46d789db6e8"`);
        await queryRunner.query(`ALTER TABLE "perinatal-disease-histories" DROP CONSTRAINT "FK_d2a3418fee48e88e60cae767553"`);
        await queryRunner.query(`ALTER TABLE "origin-medical-health-issues" DROP CONSTRAINT "FK_056cdac14043dbda6d52437f74f"`);
        await queryRunner.query(`ALTER TABLE "origin-medical-health-issues" DROP CONSTRAINT "FK_f9c3d82eb464743cc83c75f839f"`);
        await queryRunner.query(`ALTER TABLE "maternal-disease-histories" DROP CONSTRAINT "FK_2c5ebffc3bf6f324b7d0776b827"`);
        await queryRunner.query(`ALTER TABLE "maternal-disease-histories" DROP CONSTRAINT "FK_b7ee4690eaf3ae2b50a52330440"`);
        await queryRunner.query(`ALTER TABLE "disability" DROP CONSTRAINT "FK_156b26e066efaa3356529d9e8c1"`);
        await queryRunner.query(`ALTER TABLE "disability" DROP CONSTRAINT "FK_4e1282e9b626d63a610fa5ac2e1"`);
        await queryRunner.query(`ALTER TABLE "user-info" DROP CONSTRAINT "FK_737595561345b87f0f377f019ba"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "user-permissions" DROP CONSTRAINT "FK_95ae8c92259717c22ced22437bc"`);
        await queryRunner.query(`ALTER TABLE "user-permissions" DROP CONSTRAINT "FK_5012f73c39824319d792beb4a14"`);
        await queryRunner.query(`ALTER TABLE "role-permissions" DROP CONSTRAINT "FK_92ee53f7b01b6aaf1e6eac3297e"`);
        await queryRunner.query(`ALTER TABLE "role-permissions" DROP CONSTRAINT "FK_832f9475661d055310963d2f20d"`);
        await queryRunner.query(`ALTER TABLE "user-passwords" DROP CONSTRAINT "FK_5206638ec85da31e05b0a12f0a7"`);
        await queryRunner.query(`ALTER TABLE "user-address-streets" DROP CONSTRAINT "FK_c8e76646eafb2e8f7f75615701a"`);
        await queryRunner.query(`ALTER TABLE "request-contexts" DROP CONSTRAINT "FK_30a8088b8ef1b135844c0a72f5d"`);
        await queryRunner.query(`ALTER TABLE "reconsideration-requests" DROP CONSTRAINT "FK_2d6d0e59b5b35f639271e8637d7"`);
        await queryRunner.query(`ALTER TABLE "form-requests" DROP CONSTRAINT "FK_e364eaa655ada96d02fdcf3b5e6"`);
        await queryRunner.query(`ALTER TABLE "form-requests" DROP CONSTRAINT "FK_30c457ae8403a4f288d34c003d4"`);
        await queryRunner.query(`ALTER TABLE "form-requests" DROP CONSTRAINT "FK_e97d78e6f5ebf0ba0f2027e0dcc"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_e635f8de2abc09c58f97c5ce70e"`);
        await queryRunner.query(`ALTER TABLE "contextual-factors" DROP CONSTRAINT "FK_aa2550f12969f7f826dcaf9fd5e"`);
        await queryRunner.query(`ALTER TABLE "support-products-request" DROP CONSTRAINT "FK_37ff38de82808f1881f809a25b8"`);
        await queryRunner.query(`ALTER TABLE "support-products-request" DROP CONSTRAINT "FK_365152911d94485c7dff0d60832"`);
        await queryRunner.query(`ALTER TABLE "contextual-factor-questions" DROP CONSTRAINT "FK_6797a24e092c9d014bb408a19eb"`);
        await queryRunner.query(`ALTER TABLE "contextual-factor-questions" DROP CONSTRAINT "FK_16bc53284ed6f32ac9a3c20d9fa"`);
        await queryRunner.query(`ALTER TABLE "biomedicals" DROP CONSTRAINT "FK_aea07b2976ba5bea3b2c4cfc0d8"`);
        await queryRunner.query(`ALTER TABLE "perinatal-histories" DROP CONSTRAINT "FK_4f20980469108e5c8793584e933"`);
        await queryRunner.query(`ALTER TABLE "origin-medical-conditions" DROP CONSTRAINT "FK_ac046a3f787b2f1858f0e3889ae"`);
        await queryRunner.query(`ALTER TABLE "maternal-histories" DROP CONSTRAINT "FK_80cceb61be6bd21ad5b8968a7f0"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_2b475230c3a4f66ba8220d3b0d3"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_b8bc48e128daefdb56982dd122e"`);
        await queryRunner.query(`ALTER TABLE "analysis-cases" DROP CONSTRAINT "FK_b665b0e8078516816572651674e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d49e50167d6994a3ec79063b32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77071a540de3478df89f4b1b10"`);
        await queryRunner.query(`DROP TABLE "treating-physicians-requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7cc567f63ece1a0cf04bf86e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3bf0631670016021cb0ac15e1"`);
        await queryRunner.query(`DROP TABLE "treating-physician-therapeutic-interventions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b2bc49db43ea90db7b9041347"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_258bb0521512603b79ad2017d7"`);
        await queryRunner.query(`DROP TABLE "user-requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b1870a0bf21f1f926d3943d24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8baf6a8ede8bd020f135a4272b"`);
        await queryRunner.query(`DROP TABLE "user-files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_888eebb3ec48da5a35b2971096"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9d89d8ef9fd3fb9bf228629c4"`);
        await queryRunner.query(`DROP TABLE "user-applicant-patients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3da67687042d9e8fff6a6654a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c5d49318519a39ae9426da473"`);
        await queryRunner.query(`DROP TABLE "request-files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98a4b87b5db2d5ec1256c9d0c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_931d81402f4018949cfe9fea24"`);
        await queryRunner.query(`DROP TABLE "request-appointments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e87bbd531517d343119ee116d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e193155038b8f9b9dc01ffb2b1"`);
        await queryRunner.query(`DROP TABLE "reason-request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_004eec3a045ab8b54888a6669f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c472202a0faa6503c12e6227a4"`);
        await queryRunner.query(`DROP TABLE "communication-requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_609c6a14cfe70bdabb6ef7aa49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cac12e5ff3e6a1fa0ccd331aa"`);
        await queryRunner.query(`DROP TABLE "reconsideration-files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a694303dff07a4250575d3229"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b029cb5a7e2b4a849a1e712c8c"`);
        await queryRunner.query(`DROP TABLE "biomedical-international-classification-of-diseases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38e83825597a5fae46d789db6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2a3418fee48e88e60cae76755"`);
        await queryRunner.query(`DROP TABLE "perinatal-disease-histories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_056cdac14043dbda6d52437f74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9c3d82eb464743cc83c75f839"`);
        await queryRunner.query(`DROP TABLE "origin-medical-health-issues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c5ebffc3bf6f324b7d0776b82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7ee4690eaf3ae2b50a5233044"`);
        await queryRunner.query(`DROP TABLE "maternal-disease-histories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156b26e066efaa3356529d9e8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e1282e9b626d63a610fa5ac2e"`);
        await queryRunner.query(`DROP TABLE "disability"`);
        await queryRunner.query(`DROP TABLE "treating-physicians"`);
        await queryRunner.query(`DROP TABLE "therapeutic-interventions"`);
        await queryRunner.query(`DROP TABLE "user-info"`);
        await queryRunner.query(`DROP TYPE "public"."user-info_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user-info_identificationtype_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user-permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "role-permissions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "user-passwords"`);
        await queryRunner.query(`DROP TABLE "user-address-streets"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_type_enum"`);
        await queryRunner.query(`DROP TABLE "requests"`);
        await queryRunner.query(`DROP TYPE "public"."requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "request-contexts"`);
        await queryRunner.query(`DROP TABLE "reconsideration-requests"`);
        await queryRunner.query(`DROP TABLE "motives-request"`);
        await queryRunner.query(`DROP TABLE "form-requests"`);
        await queryRunner.query(`DROP TABLE "forms"`);
        await queryRunner.query(`DROP TYPE "public"."forms_type_enum"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TABLE "contextual-factors"`);
        await queryRunner.query(`DROP TABLE "support-products-request"`);
        await queryRunner.query(`DROP TABLE "support-products"`);
        await queryRunner.query(`DROP TABLE "contextual-factor-questions"`);
        await queryRunner.query(`DROP TABLE "question-factors"`);
        await queryRunner.query(`DROP TABLE "communications"`);
        await queryRunner.query(`DROP TABLE "biomedicals"`);
        await queryRunner.query(`DROP TABLE "international-classification-of-diseases"`);
        await queryRunner.query(`DROP TABLE "perinatal-histories"`);
        await queryRunner.query(`DROP TABLE "origin-medical-conditions"`);
        await queryRunner.query(`DROP TABLE "health-issues"`);
        await queryRunner.query(`DROP TABLE "maternal-histories"`);
        await queryRunner.query(`DROP TABLE "disease-history"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TABLE "service-appointments"`);
        await queryRunner.query(`DROP TABLE "branch-offices"`);
        await queryRunner.query(`DROP TABLE "analysis-cases"`);
        await queryRunner.query(`DROP TABLE "disability-assessments"`);
    }

}
